version: '3'

services:
  vpnswitch:
    build: .
    env_file: $PWD/.env
    privileged: true
    entrypoint: ./vpn run
    network_mode: host
    container_name: vpnswitch
    volumes:
      - $PWD/data:/data
